name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  pipeline:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.4', '8.0', '8.1', '8.2']
        symfony-version: ['^5.1', '^6.0']
        exclude:
          - php-version: '7.4'
            symfony-version: '^6.0'
    name: >-
      ${{ matrix.php-version }} with
      sf ${{ matrix.symfony-version }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Prepare
        run: |
          composer install
          composer require \
            symfony/config:${{ matrix.symfony-version }} \
            symfony/dependency-injection:${{ matrix.symfony-version }} \
            symfony/http-foundation:${{ matrix.symfony-version }} \
            symfony/http-kernel:${{ matrix.symfony-version }} \
            symfony/browser-kit:${{ matrix.symfony-version }} \
            symfony/framework-bundle:${{ matrix.symfony-version }} \
            --update-with-dependencies \
            --no-interaction

      - name: Testsuite
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs
          vendor/bin/phpstan analyse
